sudo: false
cache: bundler
language: ruby

rvm:
  - 2.3.1
  - 2.2.4
  - 2.2.0
  - 2.1.8
  - 2.1.0
  - 2.0.0-p648
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - ruby
  - ruby-head
  - jruby-9.1.5.0
  - jruby-9.0.5.0
  - jruby-head
  - rbx-2
  - rbx-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 1.9.3
    - rvm: 1.8.7
    - rvm: ruby
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: rbx-head
